name: Deploy to GitHub Pages

on:
 release:
  types: [created]
 # Trigger on changes to public/bookmarks.json
 push:
  paths:
   - "public/bookmarks.json"
 # Allows you to run this workflow manually from the Actions tab on GitHub.
 workflow_dispatch:
 # Allows external webhook trigger
 repository_dispatch:

# Allow this job to clone the repo and create a page deployment
permissions:
 contents: write
 pages: write
 id-token: write

# This ensures only one workflow runs at a time
concurrency:
 group: ${{ github.workflow }}-${{ github.ref }}
 cancel-in-progress: true

jobs:
 build:
  env:
   HUSKY: 0
  runs-on: ubuntu-latest
  steps:
   - name: Checkout your repository using git
     uses: actions/checkout@v4
   - name: Set repository URL as environment variable
     run: echo "REPO_URL=$GITHUB_SERVER_URL/$GITHUB_REPOSITORY" >> $GITHUB_ENV
   - name: Install, build, and upload your site
     uses: withastro/action@v3
     with:
      package-manager: bun

 deploy:
  needs: build
  runs-on: ubuntu-latest
  environment:
   name: github-pages
   url: ${{ steps.deployment.outputs.page_url }}
  outputs:
   page_url: ${{ steps.deployment.outputs.page_url }}
  steps:
   - name: Deploy to GitHub Pages
     id: deployment
     uses: actions/deploy-pages@v4

 psi-insights:
  needs: deploy
  env:
   RESULTS_DIR: docs/img
  runs-on: ubuntu-latest
  steps:
   - name: Checkout your repository using git
     uses: actions/checkout@v4
   - name: Setup bun
     uses: oven-sh/setup-bun@v2
   - name: Run psi-svg
     run: | # Have to be sure a folder is present if not, make it
      mkdir -p ${RESULTS_DIR}
      bunx psi-svg ${{ needs.deploy.outputs.page_url }} $RESULTS_DIR/desktop.svg -s=desktop --categories=performance,accessibility,best-practices,seo
      bunx psi-svg ${{ needs.deploy.outputs.page_url }} $RESULTS_DIR/mobile.svg -s=mobile --categories=performance,accessibility,best-practices,seo
   - name: Commit updated PageSpeed Insights SVGs
     run: |
      git add .
      git config --local user.email "actions@github.com"
      git config --local user.name "github-actions[bot]"
      git fetch origin
      git checkout main
      git diff --quiet && git diff --staged --quiet || git commit -am "chore(docs): update PageSpeed Insights SVGs [skip ci]"
      git pull --rebase
      git push
